server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9a2b4d3570e18b
    password: f0108f0325ada1
    properties:
      ssl:
        enable: false
      starttls:
        enable: true

  task:
    scheduling:
      pool:
        size: 3