server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true